<?php

/**
 * Implements hook_theme().
 */
function idix_commerce_invoice_theme($existing, $type, $theme, $path) {
  return [
    'commerce_order_invoice' => [
      'variables' => [
        'order_entity' => NULL,
        'billing_information' => NULL,
        'shipping_information' => NULL,
        'totals' => NULL,
      ]
    ],
    'profile__commerce_invoice' => [
      'template' => 'profile--commerce-invoice',
      'base hook' => 'profile',
    ],
    'html__facture' => [
      'template' => 'layout/html--facture',
      'base hook' => 'html',
    ],
    'page__facture' => [
      'template' => 'layout/page--facture',
      'base hook' => 'page',
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function idix_commerce_invoice_preprocess_profile__commerce_invoice(&$variables) {
  /** @var \Drupal\profile\Entity\Profile $profile */
  $profile = $variables['elements']['#profile'];
  $user = is_object($profile->uid) && is_object($profile->uid->entity) ? $profile->uid->entity : null;
  $address = $profile->address;

  $variables['profile_user'] = $user;
  $variables['address'] = $address;
  $variables['countries'] = \Drupal::service('address.country_repository')->getList();
}

/**
 * Implements hook_page_attachments_alter().
 */
function idix_commerce_invoice_page_attachments_alter(array &$attachments) {
  if(\Drupal::routeMatch()->getRouteName() == 'idix_commerce_invoice.invoice') {
    $attachments['#attached']['library'] = [];
  }
}